detector:
  conf_threshold: 0.1
  device: auto
  model_path: models/weights/detection/yolo13n-pose.pt
  model_type: yolo
preprocess:
  input_size:
  - 112
  - 112
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
recognition:
  backbone_type: resnet50
  device: auto
  embedding_size: 512
  similarity_threshold: 0.5
  weights_path: models/weights/recognition/CosFace/best.pth
